const navItems = [
  { id: 'dashboard', icon: '⌂', label: 'داشبورد' },
  { id: 'clients', icon: '♙', label: 'کاربران', count: '1,284' },
  { id: 'inbounds', icon: '◈', label: 'اینباندها', count: '18' },
  { id: 'subscriptions', icon: '⌁', label: 'سابسکریپشن' },
  { id: 'nodes', icon: '◉', label: 'نودها', count: '6' },
  { id: 'routing', icon: '⤢', label: 'روتینگ و خروجی' },
  { id: 'templates', icon: '▤', label: 'قالب‌ها' }
];
const systemItems = [
  { id: 'alerts', icon: '♢', label: 'اعلان‌ها', count: '3' },
  { id: 'backups', icon: '◫', label: 'پشتیبان‌گیری' },
  { id: 'settings', icon: '⚙', label: 'تنظیمات' }
];
const state = {
  page: 'dashboard',
  clients: [
    { name: 'آرمان محمدی', email: 'arman@farstar', protocol: 'VLESS', node: 'تهران • IR-01', used: 384, quota: 500, expiry: '1405/08/23', status: 'فعال', color: 'blue', initials: 'آم', multiplier: 1 },
    { name: 'Nima Studio', email: 'nima.studio', protocol: 'VMess', node: 'فنلاند • FI-02', used: 87, quota: 200, expiry: '1405/07/16', status: 'فعال', color: 'purple', initials: 'NS', multiplier: 1.2 },
    { name: 'سارا کریمی', email: 'sara.karimi', protocol: 'Trojan', node: 'آلمان • DE-01', used: 0, quota: 100, expiry: '1405/07/04', status: 'در انتظار', color: 'pink', initials: 'سک', multiplier: 1 },
    { name: 'Pixel Lab', email: 'pixel.lab', protocol: 'VLESS', node: 'ترکیه • TR-01', used: 920, quota: 1000, expiry: '1405/06/28', status: 'نزدیک سقف', color: 'orange', initials: 'PL', multiplier: 1.5 },
    { name: 'کیان رستمی', email: 'kian.r', protocol: 'Hysteria2', node: 'هلند • NL-01', used: 64, quota: 300, expiry: '1405/09/11', status: 'فعال', color: 'green', initials: 'کر', multiplier: .8 }
  ],
  multiplier: 1,
  theme: localStorage.getItem('farstar-theme') || 'dark'
};

document.documentElement.dataset.theme = state.theme;
const page = document.querySelector('#page');

function formatNumber(n) { return Number(n).toLocaleString('fa-IR'); }
function formatGB(n) { return `${Number(n).toFixed(n % 1 ? 1 : 0)} GB`; }
function navTemplate(items) { return items.map(item => `<button class="nav-item ${item.id === state.page ? 'active' : ''}" data-page="${item.id}"><span class="nav-icon">${item.icon}</span><span>${item.label}</span>${item.count ? `<small class="nav-count">${item.count}</small>` : ''}</button>`).join(''); }
function renderNav() { document.querySelector('#nav-list').innerHTML = navTemplate(navItems); document.querySelector('#system-nav').innerHTML = navTemplate(systemItems); document.querySelectorAll('[data-page]').forEach(el => el.addEventListener('click', () => { state.page = el.dataset.page; render(); closeSidebar(); })); }
function setPageTitle(title) { document.querySelector('#breadcrumb-title').textContent = title; }
function panelHead(title, sub, action = '') { return `<div class="card-head"><div><h2>${title}</h2>${sub ? `<p>${sub}</p>` : ''}</div>${action}</div>`; }

function dashboard() {
  setPageTitle('داشبورد');
  return `<div class="page-heading"><div><div class="eyebrow">مرکز کنترل • ${new Date().toLocaleDateString('fa-IR')}</div><h1>خوش اومدی، سجاد <span>✦</span></h1><p>وضعیت زیرساختت عالیه؛ همه‌چیز تحت کنترله.</p></div><div class="heading-actions"><button class="btn btn-secondary" data-action="export-report">⇩ دریافت گزارش</button><button class="btn btn-primary" data-action="add-client">＋ کاربر جدید</button></div></div>
    <div class="stats-grid">
      ${stat('کاربران آنلاین', '1,284', '▲ 12.8%', 'در ۲۴ ساعت گذشته', '♙', 'green')}
      ${stat('مصرف کل ترافیک', '8.42 TB', '▲ 8.4%', 'از ظرفیت ماهانه ۱۲ TB', '◌', 'cyan')}
      ${stat('نودهای فعال', '6 / 7', '● 85%', 'یک نود نیاز به بررسی دارد', '◉', 'primary')}
      ${stat('انقضای نزدیک', '23', 'در ۷ روز آینده', 'کاربر نیازمند تمدید', '◷', 'yellow')}
    </div>
    <div class="grid-2-1"><section class="panel-card">${panelHead('مصرف ترافیک', 'مجموع مصرف نودها در ۳۰ روز اخیر', '<select class="select-sm"><option>۳۰ روز اخیر</option><option>۷ روز اخیر</option></select>')}<div class="chart"><div class="y-axis"><span>۱.۲ TB</span><span>۸۰۰ GB</span><span>۴۰۰ GB</span><span>۰</span></div><div class="bars">${[43,58,51,70,48,76,64,82,55,73,88,68,91,78].map((h,i)=>`<div class="bar-item"><div class="bar" style="height:${h}%"></div><span>${['۱','۳','۵','۷','۹','۱۱','۱۳','۱۵','۱۷','۱۹','۲۱','۲۳','۲۵','۲۷'][i]}</span></div>`).join('')}</div></div></section>
      <section class="panel-card">${panelHead('توزیع پروتکل‌ها', 'کاربران بر اساس نوع اتصال')}<div class="donut-wrap"><div class="donut"><div class="donut-center"><b>۱,۲۸۴</b><span>کاربر فعال</span></div></div><div class="legend">${[['VLESS','38%','var(--primary)'],['VMess','26%','var(--cyan)'],['Trojan','19%','#a877ff'],['Hysteria2','10%','#f7b958'],['سایر','7%','#476985']].map(x=>`<div class="legend-row"><span class="legend-name"><i class="legend-dot" style="background:${x[2]}"></i>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div></section></div>
    <section class="panel-card no-pad table-card"><div class="table-head">${panelHead('کاربران اخیر', 'آخرین تغییرات و وضعیت اتصال', '<button class="btn btn-ghost" data-page="clients">مشاهده همه ←</button>')}</div>${clientTable(state.clients.slice(0,4))}</section>
    <section class="panel-card" style="margin-top:17px">${panelHead('دسترسی سریع', 'ابزارهای پرتکرار برای مدیریت روزانه')}<div class="quick-grid">${[['＋','ساخت کاربر','تنظیم ضریب و حجم'],['⌁','لینک سابسکریپشن','ساخت لینک جذاب'],['◉','افزودن نود','اتصال سرور جدید'],['⇩','پشتیبان‌گیری','آخرین نسخه: امروز']].map((x,i)=>`<button class="quick-card" data-action="${['add-client','subscription','add-node','backup'][i]}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></section>`;
}
function stat(label, value, foot, sub, icon, accent) { return `<article class="stat-card" style="--accent:var(--${accent})"><div class="stat-top"><span>${label}</span><i class="stat-icon">${icon}</i></div><div class="stat-value">${value}</div><div class="stat-foot"><span class="${foot.includes('▲') ? 'up' : foot.includes('نزدیک') || foot.includes('در') ? 'warn' : 'up'}">${foot}</span> <span> ${sub}</span></div></article>`; }
function clientTable(list) { return `<div class="table-wrap"><table><thead><tr><th>کاربر</th><th>پروتکل</th><th>نود</th><th>مصرف / سقف</th><th>ضریب</th><th>انقضا</th><th>وضعیت</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td><div class="user-cell"><div class="user-avatar">${c.initials}</div><div class="user-name"><b>${c.name}</b><small>${c.email}</small></div></div></td><td><span class="badge badge-blue">${c.protocol}</span></td><td>${c.node}</td><td><div style="min-width:110px"><div style="display:flex;justify-content:space-between;font-size:9px;margin-bottom:6px"><span>${formatGB(c.used)}</span><small style="color:var(--muted)">${formatGB(c.quota)}</small></div><div class="progress"><i style="width:${Math.min(c.used/c.quota*100,100)}%"></i></div></div></td><td><span class="badge ${c.multiplier === 1 ? 'badge-blue' : 'badge-yellow'}">×${c.multiplier}</span></td><td>${c.expiry}</td><td><span class="badge ${c.status === 'فعال' ? 'badge-green' : c.status === 'نزدیک سقف' ? 'badge-yellow' : 'badge-blue'}">● ${c.status}</span></td><td><button class="icon-btn" data-action="client-menu" data-email="${c.email}">⋮</button></td></tr>`).join('')}</tbody></table></div>`; }

function clientsPage() { setPageTitle('کاربران'); return `<div class="page-heading"><div><div class="eyebrow">مدیریت کاربران</div><h1>کاربران و دسترسی‌ها</h1><p>ساخت گروهی، سهمیه ترافیک، انقضا، IP limit و لینک اختصاصی هر کاربر.</p></div><div class="heading-actions"><button class="btn btn-secondary" data-action="bulk-import">⇧ ورود گروهی</button><button class="btn btn-primary" data-action="add-client">＋ کاربر جدید</button></div></div><div class="stats-grid">${stat('کل کاربران','1,284','▲ 24','این ماه','♙','primary')}${stat('فعال','1,173','91.3%','از کل کاربران','✓','green')}${stat('منقضی','64','5.0%','نیازمند تمدید','◷','yellow')}${stat('مسدود','47','3.7%','به‌دلیل سقف یا IP','⊘','red')}</div><section class="panel-card no-pad"><div class="table-head">${panelHead('فهرست کاربران','مدیریت کامل و عملیات گروهی','<button class="btn btn-secondary" data-action="filter">☷ فیلترها</button>')}</div>${clientTable(state.clients)}<div style="padding:15px 19px;color:var(--muted);font-size:9px;border-top:1px solid var(--line);display:flex;justify-content:space-between"><span>نمایش ۱ تا ۵ از ۱,۲۸۴ کاربر</span><span>‹　۱　۲　۳　›</span></div></section>`; }

function inboundsPage() { setPageTitle('اینباندها'); return `<div class="page-heading"><div><div class="eyebrow">ورودی‌های Xray</div><h1>اینباندها</h1><p>پروتکل، پورت، ترنسپورت، TLS / REALITY و کلاینت‌های متصل را یکجا مدیریت کن.</p></div><button class="btn btn-primary" data-action="add-inbound">＋ اینباند جدید</button></div><div class="page-grid">${[['VLESS + REALITY','443','tehran.farstar.ir','312 کاربر','فعال','green'],['VMess + WS + TLS','8443','de-01.farstar.ir','284 کاربر','فعال','green'],['Trojan + gRPC','2053','fi-02.farstar.ir','198 کاربر','فعال','green'],['Hysteria2','443','nl-01.farstar.ir','184 کاربر','فعال','green'],['Shadowsocks 2022','8388','tr-01.farstar.ir','171 کاربر','فعال','green'],['SOCKS / Mixed','1080','internal','135 کاربر','محدود','yellow']].map((x,i)=>`<article class="panel-card node-card"><div class="node-top"><div class="node-name"><div class="node-icon">◈</div><div><b>${x[0]}</b><small>${x[2]}</small></div></div><span class="badge badge-${x[5]}">● ${x[4]}</span></div><div class="node-metrics"><div class="metric"><small>پورت</small><b>${x[1]}</b></div><div class="metric"><small>کلاینت‌ها</small><b>${x[3]}</b></div><div class="metric"><small>آپ‌تایم</small><b class="up">99.98%</b></div><div class="metric"><small>مصرف امروز</small><b>${[1.8,2.1,1.4,1.1,0.9,.6][i]} GB</b></div></div><div style="display:flex;gap:7px;margin-top:16px"><button class="btn btn-secondary" style="flex:1">تنظیمات</button><button class="btn btn-ghost">⋮</button></div></article>`).join('')}</div>`; }

function subscriptionsPage() { setPageTitle('سابسکریپشن'); return `<div class="page-heading"><div><div class="eyebrow">Subscription Studio</div><h1>لینک‌های سابسکریپشن</h1><p>برای هر کاربر یا گروه، لینک‌های حرفه‌ای با صفحه معرفی، QR و فرمت‌های متنوع بساز.</p></div><button class="btn btn-primary" data-action="new-subscription">＋ ساخت لینک جدید</button></div><section class="sub-hero"><div class="eyebrow">FARSTAR CONNECT</div><h2>یک لینک، همه‌جا متصل</h2><p>صفحه اشتراک اختصاصی با برند شما، وضعیت لحظه‌ای حجم و انقضا، QR قابل اسکن و خروجی VLESS / Clash / JSON.</p><button class="btn btn-primary" data-action="preview-sub">پیش‌نمایش صفحه اشتراک ↗</button></section><div class="page-grid"><section class="panel-card link-card">${panelHead('لینک فعال من','پروفایل اشتراک اصلی','<span class="badge badge-green">● فعال</span>')}<div class="link-preview"><div class="qr"></div><div style="min-width:0;flex:1"><h3 style="margin-bottom:9px">سجاد • Pro Access</h3><div class="sub-url">https://sub.farstar.ir/s/9aKx2M...</div><div style="display:flex;gap:7px;margin-top:10px"><button class="btn btn-secondary" data-action="copy-sub">کپی لینک</button><button class="btn btn-ghost" data-action="show-qr">نمایش QR</button></div></div></div></section><section class="panel-card">${panelHead('تنظیمات اشتراک','قابل شخصی‌سازی برای هر گروه')}<div class="settings-list"><div class="setting-row"><div><b>فرمت خروجی</b><small>انتخاب خودکار بر اساس کلاینت</small></div><select class="select"><option>Auto / Raw / Clash / JSON</option></select></div><div class="setting-row"><div><b>برندینگ صفحه</b><small>لوگو و رنگ‌های FARSTAR</small></div><button class="switch on" data-action="toggle-switch"><i></i></button></div><div class="setting-row"><div><b>به‌روزرسانی پیشنهادی</b><small>فاصله refresh کلاینت‌ها</small></div><span style="font-size:10px;color:var(--cyan)">۱۲ ساعت</span></div></div></section></div>`; }

function nodesPage() { setPageTitle('نودها'); return `<div class="page-heading"><div><div class="eyebrow">Multi-node orchestration</div><h1>نودها و سرورها</h1><p>نودهای چندمنطقه‌ای را مانیتور کن، اینباندها را clone کن و سلامت اتصال را ببین.</p></div><button class="btn btn-primary" data-action="add-node">＋ افزودن نود</button></div><div class="page-grid">${[['تهران','IR-01','192.0.2.10','12 ms','34%','1.8 TB'],['هلسینکی','FI-02','192.0.2.20','68 ms','52%','2.4 TB'],['فرانکفورت','DE-01','192.0.2.30','81 ms','71%','1.7 TB'],['استانبول','TR-01','192.0.2.40','43 ms','45%','1.2 TB'],['آمستردام','NL-01','192.0.2.50','94 ms','38%','0.9 TB'],['سنگاپور','SG-01','192.0.2.60','166 ms','27%','0.4 TB']].map(x=>`<article class="panel-card node-card"><div class="node-top"><div class="node-name"><div class="node-icon">◉</div><div><b>${x[0]}</b><small>${x[1]} • ${x[2]}</small></div></div><span class="badge badge-green">● آنلاین</span></div><div class="node-metrics"><div class="metric"><small>پینگ</small><b class="up">${x[3]}</b></div><div class="metric"><small>CPU</small><b>${x[4]}</b></div><div class="metric"><small>مصرف ماه</small><b>${x[5]}</b></div><div class="metric"><small>وضعیت Xray</small><b class="up">Running</b></div></div><div style="display:flex;gap:7px;margin-top:16px"><button class="btn btn-secondary" style="flex:1" data-action="node-details">جزئیات</button><button class="btn btn-ghost">⋮</button></div></article>`).join('')}</div>`; }

function genericPage(title, eyebrow, description, body) { setPageTitle(title); return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div><button class="btn btn-primary" data-action="generic-add">＋ افزودن</button></div>${body}`; }
function routingPage() { return genericPage('روتینگ و خروجی','Traffic engineering','قوانین مسیریابی، WARP، proxy chain و load balancer را مدیریت کن.', `<div class="page-grid"><section class="panel-card full-span">${panelHead('قوانین فعال روتینگ','ترتیب اجرا از بالا به پایین','<button class="btn btn-secondary">＋ قانون جدید</button>')}<div class="settings-list">${[['IR domains','Direct','فعال'],['Ads & trackers','Block','فعال'],['Streaming','WARP outbound','فعال'],['Default traffic','Auto balance','فعال']].map(x=>`<div class="setting-row"><div><b>${x[0]}</b><small>geoip / geosite rule set</small></div><span class="badge badge-green">● ${x[1]}</span><span class="badge badge-blue">${x[2]}</span></div>`).join('')}</div></section></div>`); }
function templatesPage() { return genericPage('قالب‌ها','Config templates','قالب‌های آماده برای VLESS، VMess، Trojan، Hysteria2 و صفحه‌های سابسکریپشن.', `<div class="page-grid">${['VLESS + REALITY','VMess + WS + TLS','Trojan + gRPC','Hysteria2 QUIC','Subscription Premium','صفحه خوش‌آمدگویی'].map((x,i)=>`<article class="panel-card node-card"><div class="node-icon">▤</div><h3 style="margin-top:14px">${x}</h3><p style="font-size:9px;color:var(--muted);line-height:2;margin-top:6px">${i<4?'پیکربندی امن و آماده اتصال به نود':'قالب گرافیکی قابل برندینگ'}</p><button class="btn btn-secondary" style="margin-top:15px;width:100%">ویرایش قالب</button></article>`).join('')}</div>`); }
function settingsPage() { return genericPage('تنظیمات','System preferences','امنیت پنل، اتصال API، ظاهر، زبان، بکاپ و اعلان‌ها را تنظیم کن.', `<div class="page-grid"><section class="panel-card">${panelHead('اتصال و امنیت','تنظیمات اصلی پنل')}<div class="settings-list">${[['آدرس API مرکزی','https://api.farstar.ir'],['حالت اتصال','Demo / Adapter-ready'],['احراز هویت دومرحله‌ای','فعال'],['مسیر دسترسی پنل','/control/farstar']].map(x=>`<div class="setting-row"><div><b>${x[0]}</b><small>${x[1]}</small></div><button class="btn btn-ghost">ویرایش</button></div>`).join('')}</div></section><section class="panel-card">${panelHead('ضریب مصرف پیش‌فرض','این ضریب روی گزارش‌ها و سهمیه‌ها اعمال می‌شود.')}<div class="field"><label>ضریب مصرف</label><input class="input" id="global-multiplier" type="number" min="0.1" step="0.1" value="${state.multiplier}" /></div><p style="font-size:10px;color:var(--muted);line-height:2;margin-top:12px">مثال: ضریب ۱.۵ یعنی هر ۱ گیگابایت خام، ۱.۵ گیگابایت از سهمیه مصرف می‌کند.</p><button class="btn btn-primary" style="margin-top:15px" data-action="save-multiplier">ذخیره ضریب</button></section></div>`); }
function alertsPage() { return genericPage('اعلان‌ها','Notifications','هشدارهای سقف مصرف، انقضا، سلامت نود و رویدادهای امنیتی.', `<section class="panel-card no-pad">${panelHead('آخرین اعلان‌ها','۳ اعلان نیازمند توجه')}<div class="settings-list" style="padding:0 19px">${[['سقف مصرف نزدیک است','Pixel Lab به ۹۲٪ سهمیه رسیده است.','۵ دقیقه پیش','warn'],['نود نیازمند بررسی','CPU نود DE-01 برای ۱۰ دقیقه بالای ۷۰٪ است.','۳۲ دقیقه پیش','warn'],['بکاپ موفق','نسخه پشتیبان روزانه با موفقیت ساخته شد.','امروز، ۰۳:۰۰','green']].map(x=>`<div class="setting-row"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="badge badge-${x[3]==='green'?'green':'yellow'}">${x[2]}</span></div>`).join('')}</div></section>`); }
function backupsPage() { return genericPage('پشتیبان‌گیری','Backup center','از دیتابیس، تنظیمات و کلیدهای اتصال، نسخه امن و زمان‌بندی‌شده بگیر.', `<div class="page-grid"><section class="panel-card">${panelHead('آخرین پشتیبان','ذخیره‌سازی محلی + فضای ابری','<span class="badge badge-green">● سالم</span>')}<div style="font-size:28px;font-weight:700;margin:15px 0">امروز، ۰۳:۰۰</div><p style="font-size:10px;color:var(--muted)">حجم: 24.8 MB • رمزگذاری شده • شامل ۱,۲۸۴ کاربر</p><button class="btn btn-primary" style="margin-top:20px" data-action="backup">⇩ ساخت پشتیبان جدید</button></section><section class="panel-card">${panelHead('زمان‌بندی','پشتیبان‌گیری خودکار')}<div class="setting-row"><div><b>روزانه</b><small>هر روز ساعت ۰۳:۰۰</small></div><button class="switch on"><i></i></button></div><div class="setting-row"><div><b>نگهداری نسخه‌ها</b><small>۱۴ نسخه آخر</small></div><span style="color:var(--cyan);font-size:10px">فعال</span></div></section></div>`); }

function render() { renderNav(); const views = { dashboard, clients: clientsPage, inbounds: inboundsPage, subscriptions: subscriptionsPage, nodes: nodesPage, routing: routingPage, templates: templatesPage, settings: settingsPage, alerts: alertsPage, backups: backupsPage }; page.innerHTML = (views[state.page] || dashboard)(); bindActions(); }
function bindActions() { document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>{state.page=el.dataset.page;render();})); document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>handleAction(el.dataset.action, el))); }
function handleAction(action, el) {
  const actions = { 'add-client': () => openClientModal(), 'new-subscription': () => openSubscriptionModal(), 'subscription': () => { state.page='subscriptions'; render(); }, 'preview-sub': () => showToast('پیش‌نمایش صفحه اشتراک آماده شد.'), 'copy-sub': () => navigator.clipboard?.writeText('https://sub.farstar.ir/s/9aKx2M') && showToast('لینک سابسکریپشن کپی شد.'), 'show-qr': () => showToast('QR اختصاصی در نسخه نهایی از کلاینت تولید می‌شود.'), 'add-node': () => showToast('فرم اتصال نود جدید آماده‌سازی شد.'), 'add-inbound': () => showToast('فرم ساخت اینباند آماده‌سازی شد.'), 'backup': () => showToast('پشتیبان‌گیری شروع شد؛ اعلان تکمیل ارسال می‌شود.'), 'export-report': () => showToast('گزارش CSV در حالت نمایشی آماده شد.'), 'bulk-import': () => showToast('فایل CSV کاربران را انتخاب کنید.'), 'filter': () => showToast('فیلترهای پیشرفته باز شد.'), 'open-notifications': () => { state.page='alerts'; render(); }, 'toggle-theme': () => toggleTheme(), 'save-multiplier': () => saveMultiplier(), 'toggle-switch': () => el.classList.toggle('on'), 'client-menu': () => openClientModal(el.dataset.email), 'node-details': () => showToast('جزئیات سلامت نود نمایش داده شد.'), 'generic-add': () => showToast('این بخش برای عملیات جدید آماده است.') }; if (actions[action]) actions[action](); }
function openClientModal(email = '') { const client = state.clients.find(x=>x.email===email); document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop" data-action="close-modal"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>${client ? 'ویرایش کاربر' : 'ساخت کاربر جدید'}</h2><button class="icon-btn" data-action="close-modal">×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>نام نمایشی</label><input class="input" id="client-name" value="${client?.name || ''}" placeholder="مثلاً تیم طراحی" /></div><div class="field"><label>ایمیل / شناسه</label><input class="input" id="client-email" value="${client?.email || ''}" placeholder="unique@email" /></div><div class="field"><label>پروتکل</label><select class="select" id="client-protocol"><option>VLESS</option><option>VMess</option><option>Trojan</option><option>Hysteria2</option><option>Shadowsocks</option></select></div><div class="field"><label>نود</label><select class="select"><option>تهران • IR-01</option><option>فرانکفورت • DE-01</option><option>هلسینکی • FI-02</option></select></div><div class="field"><label>سهمیه ترافیک (GB)</label><input class="input" id="client-quota" type="number" value="${client?.quota || 100}" /></div><div class="field"><label>ضریب مصرف</label><input class="input" id="client-multiplier" type="number" min="0.1" step="0.1" value="${client?.multiplier || state.multiplier}" /></div><div class="field"><label>انقضا</label><input class="input" value="1405/09/30" /></div><div class="field"><label>Limit IP</label><input class="input" type="number" value="2" /></div><div class="field full"><label>توضیحات</label><input class="input" placeholder="یادداشت داخلی برای این کاربر" /></div></div><div class="modal-foot"><button class="btn btn-primary" data-action="save-client" data-email="${email}">ذخیره کاربر</button><button class="btn btn-secondary" data-action="close-modal">انصراف</button></div></div></div></div>`; document.querySelectorAll('#modal-root [data-action]').forEach(x=>x.addEventListener('click',()=>{ if(x.dataset.action==='save-client') saveClient(x.dataset.email); else closeModal(); })); }
function saveClient(email) { const name=document.querySelector('#client-name').value || 'کاربر جدید'; const id=document.querySelector('#client-email').value || `client-${Date.now()}`; const quota=Number(document.querySelector('#client-quota').value || 100); const multiplier=Number(document.querySelector('#client-multiplier').value || 1); const existing=state.clients.find(x=>x.email===email); if(existing){ Object.assign(existing,{name,quota,multiplier}); } else { state.clients.unshift({name,email:id,protocol:document.querySelector('#client-protocol').value,node:'تهران • IR-01',used:0,quota,expiry:'1405/09/30',status:'فعال',initials:name.slice(0,2),multiplier}); } closeModal(); render(); showToast(`کاربر «${name}» با ضریب ×${multiplier} ذخیره شد.`); }
function openSubscriptionModal() { document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop" data-action="close-modal"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>ساخت لینک سابسکریپشن</h2><button class="icon-btn" data-action="close-modal">×</button></div><div class="modal-body"><div class="form-grid"><div class="field full"><label>نام صفحه اشتراک</label><input class="input" value="FARSTAR Premium Access" /></div><div class="field"><label>کاربر یا گروه</label><select class="select"><option>سجاد • Pro Access</option><option>همه کاربران فعال</option><option>گروه VIP</option></select></div><div class="field"><label>مسیر لینک</label><input class="input" dir="ltr" value="/s/9aKx2M" /></div><div class="field"><label>فرمت</label><select class="select"><option>Auto</option><option>Clash / Mihomo</option><option>JSON</option><option>Raw Base64</option></select></div><div class="field"><label>مدت اعتبار لینک</label><select class="select"><option>بدون محدودیت</option><option>۳۰ روز</option><option>تا انقضای کاربر</option></select></div></div><div class="modal-foot"><button class="btn btn-primary" data-action="save-sub">ساخت لینک حرفه‌ای</button><button class="btn btn-secondary" data-action="close-modal">انصراف</button></div></div></div></div>`; document.querySelectorAll('#modal-root [data-action]').forEach(x=>x.addEventListener('click',()=>{if(x.dataset.action==='save-sub'){closeModal();showToast('لینک سابسکریپشن ساخته شد.');}else closeModal();})); }
function closeModal() { document.querySelector('#modal-root').innerHTML=''; }
function showToast(message) { const el=document.createElement('div'); el.className='toast'; el.textContent=message; document.querySelector('#toast-stack').appendChild(el); setTimeout(()=>el.remove(),3000); }
function saveMultiplier() { const v=Number(document.querySelector('#global-multiplier')?.value || 1); state.multiplier=v; showToast(`ضریب مصرف پیش‌فرض روی ×${v} ذخیره شد.`); }
function toggleTheme() { state.theme=state.theme==='dark'?'midnight':'dark'; document.documentElement.dataset.theme=state.theme; localStorage.setItem('farstar-theme',state.theme); showToast('تم پنل تغییر کرد.'); }
function closeSidebar() { document.querySelector('#sidebar').classList.remove('open'); }
document.querySelector('[data-action="open-sidebar"]').addEventListener('click',()=>document.querySelector('#sidebar').classList.add('open'));
document.querySelector('[data-action="close-sidebar"]').addEventListener('click',closeSidebar);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeSidebar();}});
render();
